# Generated by Django 5.2.17 on 2026-09-14 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INGRESO", "Ingreso (compra)"),
                            ("EGRESO", "Egreso"),
                            ("AJUSTE", "Ajuste de inventario"),
                            ("VENTA", "Venta"),
                            ("DEVOLUCION", "Devolución"),
                        ],
                        max_length=12,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "stock_anterior",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "stock_posterior",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Nro de comprobante, motivo del ajuste, etc.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_stock",
                        to="catalogo.articulo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de stock",
                "verbose_name_plural": "Movimientos de stock",
                "ordering": ["-created_at"],
            },
        ),
    ]
