# Generated by Django 5.2.17 on 2026-09-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "markup_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="MenuSemanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Lunes de la semana que arranca este menú",
                        unique=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=False,
                        help_text="La semana que está publicada ahora mismo en el sitio",
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Menú semanal",
                "verbose_name_plural": "Menús semanales",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("abreviatura", models.CharField(blank=True, max_length=10)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Unidad",
                "verbose_name_plural": "Unidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linea_negocio",
                    models.CharField(
                        choices=[
                            ("VIANDAS", "Viandas"),
                            ("CATERING", "Catering / Finger food"),
                            ("CAFE", "Café / venta directa"),
                            ("INSUMOS", "Insumos (no se vende, sólo recetas)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "markup_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Markup por defecto de los artículos de esta categoría",
                        max_digits=8,
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["linea_negocio", "orden", "nombre"],
                "unique_together": {("linea_negocio", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("codigo_barras", models.CharField(blank=True, max_length=50)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "relacion_unidades",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Cuántas unidades de uso trae la unidad de compra (ej. bidón 5L = 5000 cc)",
                        max_digits=12,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "VENTA",
                                "Venta (se vende, también puede usarse como insumo)",
                            ),
                            (
                                "INSUMO",
                                "Insumo (sólo para recetas, no se vende suelto)",
                            ),
                            ("ELABORADO", "Elaborado (tiene receta, se vende)"),
                        ],
                        default="VENTA",
                        max_length=10,
                    ),
                ),
                (
                    "precio_costo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Costo de la unidad de COMPRA (precio del proveedor)",
                        max_digits=12,
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Precio final editable. El sugerido es sólo una referencia.",
                        max_digits=12,
                    ),
                ),
                (
                    "alicuota_iva",
                    models.DecimalField(decimal_places=2, default=21, max_digits=5),
                ),
                (
                    "markup_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "stock_actual",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("controla_stock", models.BooleanField(default=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="articulos/"),
                ),
                ("visible_web", models.BooleanField(default=False)),
                ("descripcion_web", models.TextField(blank=True)),
                (
                    "requiere_consulta",
                    models.BooleanField(
                        default=False,
                        help_text="El precio/disponibilidad se confirma por WhatsApp (catering a medida, etc.)",
                    ),
                ),
                (
                    "es_vegetariano",
                    models.BooleanField(
                        default=False,
                        help_text="Sólo relevante para platos de la línea Viandas",
                    ),
                ),
                (
                    "ingredientes_texto",
                    models.TextField(
                        blank=True,
                        help_text="Referencia libre (ingredientes tal como figuraban en el catálogo viejo, antes de tener recetas reales con cantidades). No se usa para costear.",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulos",
                        to="catalogo.categoria",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articulos",
                        to="catalogo.marca",
                    ),
                ),
                (
                    "unidad_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulos_compra",
                        to="catalogo.unidad",
                    ),
                ),
                (
                    "unidad_uso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulos_uso",
                        to="catalogo.unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artículo",
                "verbose_name_plural": "Artículos",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="OpcionMenuDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("LUN", "Lunes"),
                            ("MAR", "Martes"),
                            ("MIE", "Miércoles"),
                            ("JUE", "Jueves"),
                            ("VIE", "Viernes"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "numero_opcion",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Opción 1"),
                            (2, "Opción 2"),
                            (3, "Opción 3 (vegetariana)"),
                        ]
                    ),
                ),
                (
                    "menu_semanal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="catalogo.menusemanal",
                    ),
                ),
                (
                    "plato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apariciones_en_menu",
                        to="catalogo.articulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción de menú del día",
                "verbose_name_plural": "Opciones de menú del día",
                "ordering": ["menu_semanal", "dia_semana", "numero_opcion"],
                "unique_together": {("menu_semanal", "dia_semana", "numero_opcion")},
            },
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=4, default=1, max_digits=12),
                ),
                ("observaciones", models.CharField(blank=True, max_length=255)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receta_items",
                        to="catalogo.articulo",
                    ),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usado_en_recetas",
                        to="catalogo.articulo",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de receta",
                "verbose_name_plural": "Ítems de receta",
                "unique_together": {("articulo", "insumo")},
            },
        ),
    ]
