# Generated by Django 5.2.17 on 2026-09-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="unidades_por_presentacion",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Para catering: cuántas piezas trae la presentación mínima de venta (ej. una bandeja de 12 empanaditas). En el resto de las líneas queda en 1.",
            ),
        ),
    ]
