# Generated by Django 5.2.17 on 2026-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_articulo_unidades_por_presentacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="visible_web",
            field=models.BooleanField(
                default=False,
                help_text="Con esto tildado y 'Activo' tildado, el artículo aparece en el catálogo público (Catering / Viandas a la carta) apenas guardás. No aplica a la vianda del día/semana -- eso se controla agregando el plato como opción dentro de un Menú Semanal marcado 'Activo'.",
                verbose_name="Publicado (visible en la web)",
            ),
        ),
    ]
