# Generated by Django 5.2.17 on 2026-09-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_alter_articulo_visible_web"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="precio_costo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Costo de la unidad de COMPRA (precio del proveedor). Para un Elaborado con receta cargada, este valor se recalcula solo a partir del costo real de los ingredientes al guardar -- no se edita a mano.",
                max_digits=12,
            ),
        ),
    ]
