# Generated by Django 5.2.17 on 2026-09-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_alter_articulo_precio_costo"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="costo_uso_insumo_anterior",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                editable=False,
                help_text="Uso interno: último costo x uso conocido del insumo, para detectar aumentos y armar el historial de costos.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HistorialCostoArticulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingrediente_detalle",
                    models.CharField(
                        blank=True,
                        help_text="Para elaborados: nombre(s) del/los insumo(s) de la receta que subieron de costo y motivaron este aumento. Vacío para insumos cargados a mano.",
                        max_length=255,
                    ),
                ),
                (
                    "costo_anterior",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("costo_nuevo", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "precio_venta_al_momento",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "revisado",
                    models.BooleanField(
                        default=False,
                        help_text="Tildar una vez que se revisó si corresponde ajustar el precio de venta.",
                    ),
                ),
                ("revisado_fecha", models.DateTimeField(blank=True, null=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_costos",
                        to="catalogo.articulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aumento de costo",
                "verbose_name_plural": "Historial de aumentos de costo",
                "ordering": ["-fecha"],
            },
        ),
    ]
