# Generated by Django 5.2.17 on 2026-09-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_receta_costo_uso_insumo_anterior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sector de impresión',
                'verbose_name_plural': 'Sectores de impresión',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='sectores_impresion',
            field=models.ManyToManyField(blank=True, help_text='Tildá a qué sector(es) de cocina/barra se manda la comanda de este artículo al venderlo (se puede tildar más de uno, ej. Cocina y Barra a la vez). Sin tildar ninguno = no imprime comanda aparte, sólo queda en el ticket (ej. una gaseosa envasada, o una vianda para llevar).', related_name='articulos', to='catalogo.sector', verbose_name='Sectores de impresión'),
        ),
    ]
