# Generated by Django 5.2.17 on 2026-09-14 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("clientes", "0001_initial"),
        ("facturacion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("CONVERTIDO", "Convertido en pedido"),
                            ("ABANDONADO", "Abandonado"),
                        ],
                        default="ACTIVO",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carritos",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito",
                "verbose_name_plural": "Carritos",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateField(auto_now_add=True)),
                ("fecha_retiro", models.DateField(blank=True, null=True)),
                ("hora_retiro", models.TimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADO", "Confirmado"),
                            ("EN_PREPARACION", "En preparación"),
                            ("LISTO", "Listo"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "total_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sena",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Cargado en el local"),
                            ("WEB", "Sitio / WhatsApp"),
                        ],
                        default="LOCAL",
                        max_length=10,
                    ),
                ),
                (
                    "tipo_entrega",
                    models.CharField(
                        choices=[
                            ("RETIRO", "Retiro en el local"),
                            ("DELIVERY", "Envío a domicilio"),
                        ],
                        default="RETIRO",
                        max_length=10,
                    ),
                ),
                (
                    "pago_estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PARCIAL", "Pago parcial (seña)"),
                            ("PAGADO", "Pagado"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("whatsapp_enviado", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "comprobante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="facturacion.comprobante",
                    ),
                ),
                (
                    "direccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="clientes.direccion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_cargados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PedidoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modalidad_venta",
                    models.CharField(
                        choices=[
                            ("VIANDA_DIARIA", "Vianda diaria"),
                            ("VIANDA_SEMANAL", "Vianda semanal (5 viandas)"),
                            ("A_LA_CARTA", "A la carta / venta directa"),
                            ("CATERING", "Catering"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "precio_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("observaciones", models.CharField(blank=True, max_length=255)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.articulo",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de pedido",
                "verbose_name_plural": "Ítems de pedido",
            },
        ),
        migrations.CreateModel(
            name="CarritoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "precio_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("observaciones", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.articulo",
                    ),
                ),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.carrito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de carrito",
                "verbose_name_plural": "Ítems de carrito",
                "unique_together": {("carrito", "articulo")},
            },
        ),
        migrations.CreateModel(
            name="ItemPedidoDiaSemana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("LUN", "Lunes"),
                            ("MAR", "Martes"),
                            ("MIE", "Miércoles"),
                            ("JUE", "Jueves"),
                            ("VIE", "Viernes"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "plato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.articulo",
                    ),
                ),
                (
                    "item_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selecciones_dias",
                        to="pedidos.pedidoitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Selección de día (vianda)",
                "verbose_name_plural": "Selecciones de día (vianda)",
                "unique_together": {("item_pedido", "dia_semana")},
            },
        ),
    ]
