# Generated by Django 5.2.17 on 2026-09-15 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
        ("clientes", "0001_initial"),
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="carritoitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="carrito",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Lo guarda el frontend (localStorage) para identificar el carrito sin login.",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="carritoitem",
            name="descripcion",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="carritoitem",
            name="modalidad_venta",
            field=models.CharField(
                choices=[
                    ("VIANDA_DIARIA", "Vianda diaria"),
                    ("VIANDA_SEMANAL", "Vianda semanal (5 viandas)"),
                    ("A_LA_CARTA", "A la carta / venta directa"),
                    ("CATERING", "Catering"),
                ],
                default="A_LA_CARTA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="carritoitem",
            name="requiere_consulta",
            field=models.BooleanField(
                default=False,
                help_text="Alguno de los platos elegidos es 'a consultar' -- el precio final se confirma aparte.",
            ),
        ),
        migrations.AlterField(
            model_name="carrito",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Se completa recién al confirmar el pedido -- el carrito arranca de invitado.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carritos",
                to="clientes.cliente",
            ),
        ),
        migrations.CreateModel(
            name="CarritoItemDiaSemana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("LUN", "Lunes"),
                            ("MAR", "Martes"),
                            ("MIE", "Miércoles"),
                            ("JUE", "Jueves"),
                            ("VIE", "Viernes"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "item_carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selecciones_dias",
                        to="pedidos.carritoitem",
                    ),
                ),
                (
                    "plato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogo.articulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Selección de día (carrito)",
                "verbose_name_plural": "Selecciones de día (carrito)",
                "unique_together": {("item_carrito", "dia_semana")},
            },
        ),
    ]
