# Generated by Django 5.2.17 on 2026-09-14 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FA_A", "Factura A"),
                            ("FA_B", "Factura B"),
                            ("FA_C", "Factura C"),
                            ("NC_A", "Nota de Crédito A"),
                            ("NC_B", "Nota de Crédito B"),
                            ("NC_C", "Nota de Crédito C"),
                            ("ND_A", "Nota de Débito A"),
                            ("ND_B", "Nota de Débito B"),
                            ("ND_C", "Nota de Débito C"),
                            ("NP", "Nota de Pedido (no fiscal)"),
                            ("TK", "Ticket (no fiscal)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("punto_venta", models.PositiveSmallIntegerField(default=1)),
                ("numero", models.BigIntegerField()),
                ("fecha", models.DateField(auto_now_add=True)),
                ("cliente_tipo_doc", models.CharField(default="CF", max_length=10)),
                ("cliente_nro_doc", models.CharField(default="0", max_length=20)),
                (
                    "cliente_nombre",
                    models.CharField(default="Consumidor Final", max_length=200),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuento_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "descuento_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "neto_gravado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "iva_105",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="IVA 10.5%",
                    ),
                ),
                (
                    "iva_21",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="IVA 21%",
                    ),
                ),
                (
                    "iva_27",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="IVA 27%",
                    ),
                ),
                (
                    "otros_tributos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cae", models.CharField(blank=True, max_length=20)),
                ("cae_vto", models.DateField(blank=True, null=True)),
                ("es_fiscal", models.BooleanField(default=False)),
                ("anulado", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comprobantes",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "comp_asociado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Comprobante original al que corresponde esta NC/ND",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_asociadas",
                        to="facturacion.comprobante",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comprobantes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante",
                "verbose_name_plural": "Comprobantes",
                "ordering": ["-fecha", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="ComprobanteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "precio_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "alicuota_iva",
                    models.DecimalField(decimal_places=2, default=21, max_digits=5),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "iva_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("observaciones", models.CharField(blank=True, max_length=255)),
                (
                    "articulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.articulo",
                    ),
                ),
                (
                    "comprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="facturacion.comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de comprobante",
                "verbose_name_plural": "Ítems de comprobante",
            },
        ),
        migrations.CreateModel(
            name="Numeracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FA_A", "Factura A"),
                            ("FA_B", "Factura B"),
                            ("FA_C", "Factura C"),
                            ("NC_A", "Nota de Crédito A"),
                            ("NC_B", "Nota de Crédito B"),
                            ("NC_C", "Nota de Crédito C"),
                            ("ND_A", "Nota de Débito A"),
                            ("ND_B", "Nota de Débito B"),
                            ("ND_C", "Nota de Débito C"),
                            ("NP", "Nota de Pedido (no fiscal)"),
                            ("TK", "Ticket (no fiscal)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("punto_venta", models.PositiveSmallIntegerField(default=1)),
                ("ultimo_numero", models.BigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Numeración",
                "verbose_name_plural": "Numeraciones",
                "unique_together": {("tipo", "punto_venta")},
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medio",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA_DEBITO", "Tarjeta de débito"),
                            ("TARJETA_CREDITO", "Tarjeta de crédito"),
                            ("QR", "QR / Mercado Pago"),
                            ("CUENTA_CORRIENTE", "Cuenta corriente"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Nro de tarjeta, nro de operación de MP, etc.",
                        max_length=100,
                    ),
                ),
                ("cuotas", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="facturacion.comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "monto_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monto_cierre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_efectivo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tarjeta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_qr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_ventas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTO", "Abierto"), ("CERRADO", "Cerrado")],
                        default="ABIERTO",
                        max_length=10,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turnos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno de caja",
                "verbose_name_plural": "Turnos de caja",
                "ordering": ["-fecha_apertura"],
            },
        ),
        migrations.AddField(
            model_name="comprobante",
            name="turno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comprobantes",
                to="facturacion.turno",
            ),
        ),
        migrations.CreateModel(
            name="CajaMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("EGRESO", "Egreso")],
                        max_length=10,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("concepto", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="facturacion.turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de caja",
                "verbose_name_plural": "Movimientos de caja",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="comprobante",
            unique_together={("tipo", "punto_venta", "numero")},
        ),
    ]
