# Generated by Django 5.2.17 on 2026-09-16 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_sector_articulo_sectores_impresion'),
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, help_text="Ej. 'Mesa 3', 'Barra', 'Terraza 1'.", max_length=50)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada')], default='LIBRE', max_length=10)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('turno', models.ForeignKey(blank=True, help_text='Turno de caja en el que se abrió (para poder auditar/cerrar todo junto).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='facturacion.turno')),
                ('usuario_apertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_abiertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='MesaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('precio_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sectores_enviados', models.CharField(blank=True, default='', help_text='Sectores (separados por coma) a los que ya se mandó a imprimir esta línea -- un artículo puede ir a más de un sector (ej. Cocina y Barra), y cada uno se manda por separado para no reimprimir lo que ya salió.', max_length=200)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.articulo')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.mesa')),
            ],
            options={
                'verbose_name': 'Ítem de mesa',
                'verbose_name_plural': 'Ítems de mesa',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_venta', models.PositiveSmallIntegerField(default=1)),
                ('nombre_windows', models.CharField(blank=True, help_text='Nombre exacto de la impresora tal como figura en Windows (Dispositivos e impresoras).', max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impresoras', to='catalogo.sector')),
            ],
            options={
                'verbose_name': 'Configuración de impresora',
                'verbose_name_plural': 'Configuración de impresoras',
                'ordering': ['punto_venta', 'sector__nombre'],
                'unique_together': {('sector', 'punto_venta')},
            },
        ),
    ]
