# Generated by Django 5.2.17 on 2026-09-18 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_mesa_mesaitem_configimpresora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona del salón',
                'verbose_name_plural': 'Zonas del salón',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='mesa',
            name='alto',
            field=models.PositiveSmallIntegerField(default=90, help_text='Alto en píxeles en el mapa de mesas.'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='ancho',
            field=models.PositiveSmallIntegerField(default=110, help_text='Ancho en píxeles en el mapa de mesas.'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='capacidad',
            field=models.PositiveSmallIntegerField(default=4, help_text='Cantidad de comensales.'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='forma',
            field=models.CharField(choices=[('CUADRADA', 'Cuadrada'), ('REDONDA', 'Redonda')], default='CUADRADA', max_length=10),
        ),
        migrations.AddField(
            model_name='mesa',
            name='pos_x',
            field=models.PositiveSmallIntegerField(default=20, help_text='Posición X en el mapa de mesas.'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='pos_y',
            field=models.PositiveSmallIntegerField(default=20, help_text='Posición Y en el mapa de mesas.'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('CUENTA_PEDIDA', 'Cuenta pedida'), ('RESERVADA', 'Reservada')], default='LIBRE', max_length=20),
        ),
        migrations.AddField(
            model_name='mesa',
            name='zona',
            field=models.ForeignKey(blank=True, help_text='Zona del salón (pestaña en el mapa de mesas). Sin asignar, la mesa no aparece en ningún mapa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='facturacion.zonasalon'),
        ),
    ]
