# Generated by Django 5.2.17 on 2026-09-14 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("CAJERO", "Cajero"),
                            ("VENDEDOR", "Vendedor"),
                        ],
                        default="VENDEDOR",
                        max_length=10,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("activo", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario del sistema",
                "verbose_name_plural": "Usuarios del sistema",
            },
        ),
    ]
