# Generated by Django 5.2.17 on 2026-09-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_doc", models.CharField(default="CF", max_length=10)),
                ("nro_doc", models.CharField(blank=True, max_length=20)),
                ("razon_social", models.CharField(blank=True, max_length=200)),
                ("nombre", models.CharField(blank=True, max_length=100)),
                ("apellido", models.CharField(blank=True, max_length=100)),
                ("domicilio", models.CharField(blank=True, max_length=255)),
                (
                    "localidad",
                    models.CharField(blank=True, default="Rosario", max_length=100),
                ),
                (
                    "provincia",
                    models.CharField(blank=True, default="Santa Fe", max_length=100),
                ),
                ("cp", models.CharField(blank=True, max_length=10)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=150)),
                (
                    "condicion_iva",
                    models.CharField(
                        choices=[
                            ("CF", "Consumidor Final"),
                            ("RI", "Responsable Inscripto"),
                            ("MONOTRIBUTO", "Monotributo"),
                            ("EXENTO", "Exento"),
                        ],
                        default="CF",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("acepta_promo", models.BooleanField(default=False)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="clientes/"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ClienteAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo_auth",
                    models.CharField(
                        choices=[("WHATSAPP", "WhatsApp"), ("EMAIL", "Email")],
                        max_length=10,
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        help_text="El número de WhatsApp o el email usado para loguearse",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("verificado", models.BooleanField(default=False)),
                ("codigo_verificacion", models.CharField(blank=True, max_length=10)),
                (
                    "codigo_verificacion_exp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reset_token", models.CharField(blank=True, max_length=100)),
                ("reset_token_exp", models.DateTimeField(blank=True, null=True)),
                ("intentos_fallidos", models.PositiveSmallIntegerField(default=0)),
                ("bloqueado_hasta", models.DateTimeField(blank=True, null=True)),
                ("ultimo_login", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acceso web de cliente",
                "verbose_name_plural": "Accesos web de clientes",
            },
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(default="Casa", max_length=50)),
                ("direccion", models.CharField(max_length=255)),
                (
                    "localidad",
                    models.CharField(blank=True, default="Rosario", max_length=100),
                ),
                (
                    "provincia",
                    models.CharField(blank=True, default="Santa Fe", max_length=100),
                ),
                ("cp", models.CharField(blank=True, max_length=10)),
                ("referencia", models.CharField(blank=True, max_length=255)),
                ("es_default", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direcciones",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección",
                "verbose_name_plural": "Direcciones",
                "ordering": ["-es_default", "-created_at"],
            },
        ),
    ]
