# Generated by Django 5.2.17 on 2026-09-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        blank=True,
                        help_text="Ej. Coffee break, cumpleaños, evento de empresa",
                        max_length=100,
                    ),
                ),
                ("fecha_evento", models.DateField()),
                ("hora_evento", models.TimeField(blank=True, null=True)),
                (
                    "cantidad_personas",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "en_el_local",
                    models.BooleanField(
                        default=False,
                        help_text="Desmarcado = el evento es en la dirección del cliente/otro lugar",
                    ),
                ),
                (
                    "lugar_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del salón/oficina, referencia, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "sena",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CONSULTADA", "Consultada (a confirmar)"),
                            ("CONFIRMADA", "Confirmada"),
                            ("SENADA", "Confirmada con seña"),
                            ("CANCELADA", "Cancelada"),
                            ("REALIZADA", "Realizada"),
                        ],
                        default="CONSULTADA",
                        max_length=12,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas_evento",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "direccion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dirección del evento, si no es en el local",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_evento",
                        to="clientes.direccion",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se completa cuando la reserva se convierte en un pedido de catering concreto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reserva_evento",
                        to="pedidos.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de evento/catering",
                "verbose_name_plural": "Reservas de evento/catering",
                "ordering": ["fecha_evento", "hora_evento"],
            },
        ),
        migrations.CreateModel(
            name="ReservaMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("cantidad_personas", models.PositiveSmallIntegerField(default=2)),
                (
                    "zona_mesa",
                    models.CharField(
                        blank=True, help_text="Ej. Salón, vereda, mesa 4", max_length=50
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("REALIZADA", "Realizada"),
                        ],
                        default="CONFIRMADA",
                        max_length=12,
                    ),
                ),
                ("observaciones", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas_mesa",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de mesa",
                "verbose_name_plural": "Reservas de mesa",
                "ordering": ["fecha", "hora"],
            },
        ),
    ]
